### ISSUE TITLE
[macOS] Execution Error: Screenshot attached

### ISSUE THREAD

**Issue by neosalmon** [pacocoursey/Home#1]
I followed the instructions from the README, only to end up here;
<img width="1680" alt="screen shot 2018-06-30 at 5 44 22 am" src="https://user-images.githubusercontent.com/40545794/42125310-06b39d82-7c29-11e8-951e-0122cc8f454e.png">

**Comment by pacocoursey** [comment]
Hi, do you still need help with this?
